name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x android-launcher/gradlew
      
    - name: Build Debug APK
      run: |
        cd android-launcher
        ./gradlew assembleDebug --stacktrace
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: MinLauncher-Debug-APK
        path: android-launcher/app/build/outputs/apk/debug/app-debug.apk
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: MinLauncher v1.0.${{ github.run_number }}
        body: |
          Minimal Android Launcher
          
          Features:
          - Pure black background
          - White text only, no icons
          - Monospace font
          - Shows only essential apps
          - Clean, distraction-free design
          
          To install: Download the APK, enable "Install from unknown sources" in your Android settings, and install the APK file.
        draft: false
        prerelease: false
        files: android-launcher/app/build/outputs/apk/debug/app-debug.apk